version: '3.8'

services:
  webapp:
    image: web:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDb;User=sa;Password=123456789!@#aA;
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "123456789!@#aA"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
